#!/bin/bash

echo "🔄 仓库重命名指南"
echo ""

echo "📋 当前情况："
echo "   仓库名: EasonAI.github.io"
echo "   用户名: EasonAI-5589"
echo "   当前URL: https://easonai-5589.github.io/EasonAI.github.io/"
echo ""

echo "🎯 期望结果："
echo "   仓库名: EasonAI-5589.github.io"
echo "   用户名: EasonAI-5589"
echo "   新URL: https://EasonAI-5589.github.io"
echo ""

echo "📝 重命名步骤："
echo ""
echo "1. 访问GitHub仓库设置页面："
echo "   https://github.com/EasonAI-5589/EasonAI.github.io/settings"
echo ""
echo "2. 滚动到页面底部，找到'Repository name'部分"
echo ""
echo "3. 将名称从 'EasonAI.github.io' 改为 'EasonAI-5589.github.io'"
echo ""
echo "4. 点击'Rename'按钮"
echo ""
echo "5. 重命名完成后，运行以下命令更新本地仓库："
echo ""
echo "   cd /Users/guoyichen/EasonAI/academicpages-website"
echo "   git remote set-url origin https://github.com/EasonAI-5589/EasonAI-5589.github.io.git"
echo "   git remote -v"
echo "   git push origin main"
echo ""
echo "⏰ 等待时间："
echo "   重命名后等待5-15分钟让新URL生效"
echo ""
echo "✅ 验证："
echo "   访问 https://EasonAI-5589.github.io 确认网站正常"
echo ""
echo "📌 注意事项："
echo "   - 重命名后旧URL将不再工作"
echo "   - GitHub Pages会自动重新部署"
echo "   - 记得更新所有引用旧URL的地方"
